# Generated by Django 5.0.6 on 2024-12-18 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('courseFirstChoice', models.CharField(max_length=100)),
                ('courseSecondChoice', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('guardiansPhoneNumber', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('student_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('communityhealth', 'Communityhealth'), ('medlab', 'Medlab'), ('pharmacy', 'Pharmacy'), ('dot', 'Dot')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], max_length=10)),
                ('level', models.CharField(choices=[('100lv', '100 Level'), ('200lv', '200 Level'), ('300lv', '300 Level')], max_length=10)),
                ('credit_load', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('favorite_subject', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('school_name', models.CharField(max_length=100)),
                ('favorite_subject', models.CharField(max_length=50)),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('lga', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('load', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_hostel', models.CharField(choices=[('Hostel A', 'Hostel A'), ('Hostel B', 'Hostel B'), ('Hostel C', 'Hostel C')], max_length=20)),
                ('chosen_floor', models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('First Floor', 'First Floor'), ('Second Floor', 'Second Floor')], max_length=20)),
                ('room', models.CharField(choices=[('Room 1', 'Room 1'), ('Room 2', 'Room 2'), ('Room 3', 'Room 3')], max_length=20)),
                ('bed_space', models.CharField(choices=[('Bed 1', 'Bed 1'), ('Bed 2', 'Bed 2'), ('Bed 3', 'Bed 3')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
        ),
    ]
