# Generated by Django 5.0.6 on 2025-01-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionform',
            old_name='student_id',
            new_name='reg_number',
        ),
    ]
