# Generated by Django 5.0.6 on 2024-07-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
