# Generated by Django 5.0.6 on 2024-09-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_course_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], max_length=10)),
                ('level', models.CharField(choices=[('100lv', '100 Level'), ('200lv', '200 Level'), ('300lv', '300 Level')], max_length=10)),
                ('credit_load', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseRegistration',
        ),
    ]
