# Generated by Django 5.0.6 on 2024-09-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_artscourses_commercialcourses_sciencecourses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScienceCourses',
            new_name='EngineeringCourses',
        ),
    ]
