# Generated by Django 5.0.6 on 2024-09-13 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_course_courseregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtsCourses',
        ),
        migrations.DeleteModel(
            name='CommercialCourses',
        ),
        migrations.DeleteModel(
            name='EngineeringCourses',
        ),
        migrations.DeleteModel(
            name='MedicalCourses',
        ),
        migrations.RenameField(
            model_name='courseregistration',
            old_name='date_registered',
            new_name='registered_on',
        ),
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_load',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('medical', 'Medical'), ('engineering', 'Engineering'), ('science', 'Science'), ('art', 'Art'), ('commerce', 'Commerce')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('100lv', '100 Level'), ('200lv', '200 Level'), ('300lv', '300 Level')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student'),
        ),
    ]
